package:
  name: broker
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../


build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - numpy

test:
  requires:
    - nose
  imports:
     - broker
     - broker.server
     - broker.client

about:
  license: 3-Clause BSD
